replacement of formatted strings with format() due to a NotImplementedError from numba
NotImplementedError: Failed in object mode pipeline (step: analyzing bytecode)
Use of unknown opcode FORMAT_VALUE

see https://github.com/numba/numba/issues/3250

#306